### ISSUE TITLE
Unknown physical type: 1starmotelUnknown physical type: poisondartfrog

### ISSUE THREAD

**Issue by ruderik** [Technical-13/MunzeeMap-Filter#24]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/1starmotel.png is a physical: ![1starmotel](https://munzee.global.ssl.fastly.net/images/pins/1starmotel.png)
* [Walkway to station](https://www.munzee.com/m/egginthesky/189) at [51.523017870815, -0.25857593558203](https://www.munzee.com/map/gcpv457xq/20.0) by [egginthesky](https://www.munzee.com/m/egginthesky)

https://munzee.global.ssl.fastly.net/images/pins/poisondartfrog.png is a physical: ![poisondartfrog](https://munzee.global.ssl.fastly.net/images/pins/poisondartfrog.png)
* [IC 689](https://www.munzee.com/m/Peter1980/3358) at [51.52455996574882, -0.3247122852439338](https://www.munzee.com/map/gcpv0eg83/20.0) by [Peter1980](https://www.munzee.com/m/Peter1980)

**Comment by Technical-13** [comment]
Resolved in https://github.com/Technical-13/MunzeeMap-Filter/commit/702c6190b0cd50354429e8ffeee0fa5ff2e923d8
