### ISSUE TITLE
Unknown type: [ "virtual", "electricmystery" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#33]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/electricmystery.png is a virtual: ![electricmystery](https://munzee.global.ssl.fastly.net/images/pins/electricmystery.png)
* [Electric @ Dallas by Sandy13 UK ](https://www.munzee.com/m/Sandy13/4590) at [32.778780514885, -96.80780142429357](https://www.munzee.com/map/9vg4mp4wn/20.0) by [Sandy13](https://www.munzee.com/m/Sandy13)

**Comment by Technical-13** [comment]
Resolved as part of #34
