### ISSUE TITLE
Unknown types: [ "virtual", "electricmystery" ], [ "virtual", "oniks" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#34]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/electricmystery.png is a virtual: ![electricmystery](https://munzee.global.ssl.fastly.net/images/pins/electricmystery.png)
* [Electric @ Dallas by Sandy13 UK ](https://www.munzee.com/m/Sandy13/4590) at [32.778780514885, -96.80780142429357](https://www.munzee.com/map/9vg4mp4wn/20.0) by [Sandy13](https://www.munzee.com/m/Sandy13)

https://munzee.global.ssl.fastly.net/images/pins/oniks.png is a virtual: ![oniks](https://munzee.global.ssl.fastly.net/images/pins/oniks.png)
* [Gorgathan lived not far from here](https://www.munzee.com/m/Gorgathan/190) at [51.892808640645, -0.46967479194643147](https://www.munzee.com/map/gcpxjqf18/20.0) by [Gorgathan](https://www.munzee.com/m/Gorgathan)

**Comment by Technical-13** [comment]
Fixed in 29a5bcfe7fce45e2f3f2e89bc4fd21b3f85a0540 and 4d8bc9657b378002891874bfbabd074fc14f2bbd
