### ISSUE TITLE
Unknown type: [ "virtual", "yellowwaterballoon" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#35]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/yellowwaterballoon.png is a virtual: ![yellowwaterballoon](https://munzee.global.ssl.fastly.net/images/pins/yellowwaterballoon.png)
* [Bumble Bee #1](https://www.munzee.com/m/war1man/12418) at [51.9018034, -0.5153045898](https://www.munzee.com/map/gcpxk22vb/20.0) by [war1man](https://www.munzee.com/m/war1man)

**Comment by Technical-13** [comment]
Temporary type that'll leave the map soon, not adding it.
