### ISSUE TITLE
Unknown types: [ "virtual", "minotaurcyclops" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#36]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/minotaurcyclops.png is a virtual: ![minotaurcyclops](https://munzee.global.ssl.fastly.net/images/pins/minotaurcyclops.png)
* [Bones M1 C/Bow Junc 10](https://www.munzee.com/m/Bones/3687) at [51.854893872947, -0.42427382672175895](https://www.munzee.com/map/gcpwyrgh9/20.0) by [Bones](https://www.munzee.com/m/Bones)

**Comment by Technical-13** [comment]
Fixed in 662195a8505d1d5e4e9c9753fe332f5aaf7ec5b4
