### ISSUE TITLE
 Whoa there!  Your request URL is too long. Contact Support — GitHub Status — @githubstatus

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#37]
`https://github.com/Technical-13/MunzeeMap-Filter/issues/new?title=Unknown types%3A [ "virtual"%2C "yellowwaterballoon" ], [ "physical"%2C "pb%26jellyfish" ], [ "virtual"%2C "planulalarva" ], [ "virtual"%2C "polypwithbulbs" ], [ "virtual"%2C "virtualonyx" ], [ "virtual"%2C "virtualcitrine" ], [ "virtual"%2C "greenwaterballoon" ], [ "virtual"%2C "ametust" ], [ "virtual"%2C "elekter" ], [ "physical"%2C "magnetus" ], [ "physical"%2C "goldenjellyfish" ], [ "physical"%2C "treefrog" ], [ "virtual"%2C "bluewaterballoon" ], [ "virtual"%2C "sirprizewheel" ]&body=Found unknown mapMarker types%3A%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fyellowwaterballoon.png is a virtual%3A ![yellowwaterballoon](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fyellowwaterballoon.png)%0A* [Bumble Bee %231](https%3A%2F%2Fwww.munzee.com%2Fm%2Fwar1man%2F12418) at [51.9018034%2C -0.5153045898](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcpxk22vb%2F20.0) by [war1man](https%3A%2F%2Fwww.munzee.com%2Fm%2Fwar1man)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpb%26jellyfish.png is a physical%3A ![pb%26jellyfish](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpb%26jellyfish.png)%0A* [Green box](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmickyz%2F3607) at [50.886658332716%2C -1.3208669889731](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp13zwhm%2F20.0) by [mickyz](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmickyz)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fplanulalarva.png is a virtual%3A ![planulalarva](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fplanulalarva.png)%0A* [Bursledon](https%3A%2F%2Fwww.munzee.com%2Fm%2Ftonydev%2F4568) at [50.889022528943%2C -1.2962132198326515](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d804h%2F20.0) by [tonydev](https%3A%2F%2Fwww.munzee.com%2Fm%2Ftonydev)%0A* [Jellyfish %40 M27%20 by Sandy13](https%3A%2F%2Fwww.munzee.com%2Fm%2FSandy13%2F5100) at [50.90325260259%2C -1.3149959277839685](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d4dky%2F20.0) by [Sandy13](https%3A%2F%2Fwww.munzee.com%2Fm%2FSandy13)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpolypwithbulbs.png is a virtual%3A ![polypwithbulbs](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpolypwithbulbs.png)%0A* [Quick Deploy by MogwaiLiz](https%3A%2F%2Fwww.munzee.com%2Fm%2FMogwaiLiz%2F2144) at [50.890470990596%2C -1.303271443833495](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d26fr%2F20.0) by [MogwaiLiz](https%3A%2F%2Fwww.munzee.com%2Fm%2FMogwaiLiz)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualonyx.png is a virtual%3A ![virtualonyx](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualonyx.png)%0A* [Quick Deploy by Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix%2F4281) at [50.899178581143%2C -1.4071459927191654](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncxczm5%2F20.0) by [Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix)%0A* [Quick Deploy by chimem](https%3A%2F%2Fwww.munzee.com%2Fm%2Fchimem%2F3607) at [50.936336716805%2C -1.4048630590407356](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1b09j8%2F20.0) by [chimem](https%3A%2F%2Fwww.munzee.com%2Fm%2Fchimem)%0A* [Lovers Onyx](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5663) at [50.932861039956%2C -1.4018979488998582](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1b051m%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Lovers Onyx](https%3A%2F%2Fwww.munzee.com%2Fm%2FTinyTrio%2F3902) at [50.932623940715%2C -1.4018051962347329](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1b050p%2F20.0) by [TinyTrio](https%3A%2F%2Fwww.munzee.com%2Fm%2FTinyTrio)%0A* [Southampton Old Cemetary Onyx](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5661) at [50.921833014014%2C -1.4149567393025393](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncxy19j%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualcitrine.png is a virtual%3A ![virtualcitrine](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualcitrine.png)%0A* [Quick Deploy by Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix%2F4556) at [50.903684625046%2C -1.397616080913167](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp184wr3%2F20.0) by [Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix)%0A* [Quick Deploy by Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix%2F4276) at [50.915180047415%2C -1.523991754256997](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcnctkf62%2F20.0) by [Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix)%0A* [Calmore Corner Virtual Citrine](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmrandcr%2F158) at [50.91750418678237%2C -1.5056894203123647](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncttpxg%2F20.0) by [mrandcr](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmrandcr)%0A* [Lovers Citrine](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5664) at [50.932444881543%2C -1.4027192477123833](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pfwf%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Southampton Old Cemetary Citrine](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5662) at [50.91968462534%2C -1.4153798422462103](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncxv9ke%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgreenwaterballoon.png is a virtual%3A ![greenwaterballoon](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgreenwaterballoon.png)%0A* [NFC Newcliffe Gardens](https%3A%2F%2Fwww.munzee.com%2Fm%2FDynamiteDunx%2F1819) at [50.9099200858259%2C -1.30799196660519](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d5zec%2F20.0) by [DynamiteDunx](https%3A%2F%2Fwww.munzee.com%2Fm%2FDynamiteDunx)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fametust.png is a virtual%3A ![ametust](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fametust.png)%0A* [Virtual Black Munzee World Travels Garden %2310](https%3A%2F%2Fwww.munzee.com%2Fm%2Fdielange%2F466) at [50.93542735%2C -1.331348839](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1c8w83%2F20.0) by [dielange](https%3A%2F%2Fwww.munzee.com%2Fm%2Fdielange)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Felekter.png is a virtual%3A ![elekter](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Felekter.png)%0A* [M27 MVM](https%3A%2F%2Fwww.munzee.com%2Fm%2Fstaticalbatross%2F973) at [50.916111551075%2C -1.3183070123195648](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1dhbpc%2F20.0) by [staticalbatross](https%3A%2F%2Fwww.munzee.com%2Fm%2Fstaticalbatross)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fmagnetus.png is a physical%3A ![magnetus](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fmagnetus.png)%0A* [Phone Box](https%3A%2F%2Fwww.munzee.com%2Fm%2FRustyChacon%2F604) at [50.935242320586596%2C -1.4764735847711563](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncy2kz7%2F20.0) by [RustyChacon](https%3A%2F%2Fwww.munzee.com%2Fm%2FRustyChacon)%0A* [TGS Yew Road](https%3A%2F%2Fwww.munzee.com%2Fm%2Fthegr8simondo%2F718) at [50.9193318%2C -1.3548211](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp19jt6w%2F20.0) by [thegr8simondo](https%3A%2F%2Fwww.munzee.com%2Fm%2Fthegr8simondo)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgoldenjellyfish.png is a physical%3A ![goldenjellyfish](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgoldenjellyfish.png)%0A* [Riverside-Doggy bin](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob%2F234) at [50.9318288%2C -1.3761882](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18xvgk%2F20.0) by [HideyRob](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Ftreefrog.png is a physical%3A ![treefrog](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Ftreefrog.png)%0A* [Riverside-Doggy bin](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob%2F251) at [50.9321511%2C -1.3799991](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18xgj7%2F20.0) by [HideyRob](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fbluewaterballoon.png is a virtual%3A ![bluewaterballoon](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fbluewaterballoon.png)%0A* [Quick Deploy by OldFruits](https%3A%2F%2Fwww.munzee.com%2Fm%2FOldFruits%2F3195) at [50.931883068539%2C -1.3997696870026175](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18puex%2F20.0) by [OldFruits](https%3A%2F%2Fwww.munzee.com%2Fm%2FOldFruits)%0A%0A2412 is a virtual%3A ![sirprizewheel](2412)%0A* [Quick Deploy by Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5736) at [50.931607153173%2C -1.4053645126023184](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pbdh%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Quick Deploy by Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5737) at [50.93227142538%2C -1.403881113938212](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pctz%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Quick Deploy by Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5738) at [50.931828578178%2C -1.4015974610119315](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pg7k%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)`

```
Whoa there!

Your request URL is too long.
Contact Support — GitHub Status — @githubstatus
```

**Comment by JonnyTech** [comment]
`https://github.com/Technical-13/MunzeeMap-Filter/issues/new?title=Unknown types%3A [ "virtual"%2C "yellowwaterballoon" ], [ "physical"%2C "pb%26jellyfish" ], [ "virtual"%2C "planulalarva" ], [ "virtual"%2C "polypwithbulbs" ], [ "virtual"%2C "virtualonyx" ], [ "virtual"%2C "virtualcitrine" ], [ "virtual"%2C "greenwaterballoon" ], [ "virtual"%2C "ametust" ], [ "virtual"%2C "elekter" ], [ "physical"%2C "magnetus" ], [ "physical"%2C "goldenjellyfish" ], [ "physical"%2C "treefrog" ], [ "virtual"%2C "bluewaterballoon" ], [ "virtual"%2C "sirprizewheel" ], [ "virtual"%2C "polyp" ]&body=Found unknown mapMarker types%3A%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fyellowwaterballoon.png is a virtual%3A ![yellowwaterballoon](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fyellowwaterballoon.png)%0A* [Bumble Bee %231](https%3A%2F%2Fwww.munzee.com%2Fm%2Fwar1man%2F12418) at [51.9018034%2C -0.5153045898](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcpxk22vb%2F20.0) by [war1man](https%3A%2F%2Fwww.munzee.com%2Fm%2Fwar1man)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpb%26jellyfish.png is a physical%3A ![pb%26jellyfish](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpb%26jellyfish.png)%0A* [Green box](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmickyz%2F3607) at [50.886658332716%2C -1.3208669889731](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp13zwhm%2F20.0) by [mickyz](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmickyz)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fplanulalarva.png is a virtual%3A ![planulalarva](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fplanulalarva.png)%0A* [Bursledon](https%3A%2F%2Fwww.munzee.com%2Fm%2Ftonydev%2F4568) at [50.889022528943%2C -1.2962132198326515](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d804h%2F20.0) by [tonydev](https%3A%2F%2Fwww.munzee.com%2Fm%2Ftonydev)%0A* [Jellyfish %40 M27%20 by Sandy13](https%3A%2F%2Fwww.munzee.com%2Fm%2FSandy13%2F5100) at [50.90325260259%2C -1.3149959277839685](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d4dky%2F20.0) by [Sandy13](https%3A%2F%2Fwww.munzee.com%2Fm%2FSandy13)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpolypwithbulbs.png is a virtual%3A ![polypwithbulbs](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpolypwithbulbs.png)%0A* [Quick Deploy by MogwaiLiz](https%3A%2F%2Fwww.munzee.com%2Fm%2FMogwaiLiz%2F2144) at [50.890470990596%2C -1.303271443833495](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d26fr%2F20.0) by [MogwaiLiz](https%3A%2F%2Fwww.munzee.com%2Fm%2FMogwaiLiz)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualonyx.png is a virtual%3A ![virtualonyx](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualonyx.png)%0A* [Quick Deploy by Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix%2F4281) at [50.899178581143%2C -1.4071459927191654](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncxczm5%2F20.0) by [Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix)%0A* [Quick Deploy by chimem](https%3A%2F%2Fwww.munzee.com%2Fm%2Fchimem%2F3607) at [50.936336716805%2C -1.4048630590407356](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1b09j8%2F20.0) by [chimem](https%3A%2F%2Fwww.munzee.com%2Fm%2Fchimem)%0A* [Lovers Onyx](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5663) at [50.932861039956%2C -1.4018979488998582](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1b051m%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Lovers Onyx](https%3A%2F%2Fwww.munzee.com%2Fm%2FTinyTrio%2F3902) at [50.932623940715%2C -1.4018051962347329](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1b050p%2F20.0) by [TinyTrio](https%3A%2F%2Fwww.munzee.com%2Fm%2FTinyTrio)%0A* [Southampton Old Cemetary Onyx](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5661) at [50.921833014014%2C -1.4149567393025393](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncxy19j%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualcitrine.png is a virtual%3A ![virtualcitrine](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fvirtualcitrine.png)%0A* [Quick Deploy by Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix%2F4556) at [50.903684625046%2C -1.397616080913167](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp184wr3%2F20.0) by [Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix)%0A* [Quick Deploy by Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix%2F4276) at [50.915180047415%2C -1.523991754256997](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcnctkf62%2F20.0) by [Pixiewix](https%3A%2F%2Fwww.munzee.com%2Fm%2FPixiewix)%0A* [Calmore Corner Virtual Citrine](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmrandcr%2F158) at [50.91750418678237%2C -1.5056894203123647](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncttpxg%2F20.0) by [mrandcr](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmrandcr)%0A* [Lovers Citrine](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5664) at [50.932444881543%2C -1.4027192477123833](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pfwf%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Southampton Old Cemetary Citrine](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5662) at [50.91968462534%2C -1.4153798422462103](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncxv9ke%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgreenwaterballoon.png is a virtual%3A ![greenwaterballoon](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgreenwaterballoon.png)%0A* [NFC Newcliffe Gardens](https%3A%2F%2Fwww.munzee.com%2Fm%2FDynamiteDunx%2F1819) at [50.9099200858259%2C -1.30799196660519](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1d5zec%2F20.0) by [DynamiteDunx](https%3A%2F%2Fwww.munzee.com%2Fm%2FDynamiteDunx)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fametust.png is a virtual%3A ![ametust](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fametust.png)%0A* [Virtual Black Munzee World Travels Garden %2310](https%3A%2F%2Fwww.munzee.com%2Fm%2Fdielange%2F466) at [50.93542735%2C -1.331348839](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1c8w83%2F20.0) by [dielange](https%3A%2F%2Fwww.munzee.com%2Fm%2Fdielange)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Felekter.png is a virtual%3A ![elekter](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Felekter.png)%0A* [M27 MVM](https%3A%2F%2Fwww.munzee.com%2Fm%2Fstaticalbatross%2F973) at [50.916111551075%2C -1.3183070123195648](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp1dhbpc%2F20.0) by [staticalbatross](https%3A%2F%2Fwww.munzee.com%2Fm%2Fstaticalbatross)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fmagnetus.png is a physical%3A ![magnetus](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fmagnetus.png)%0A* [Phone Box](https%3A%2F%2Fwww.munzee.com%2Fm%2FRustyChacon%2F604) at [50.935242320586596%2C -1.4764735847711563](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcncy2kz7%2F20.0) by [RustyChacon](https%3A%2F%2Fwww.munzee.com%2Fm%2FRustyChacon)%0A* [TGS Yew Road](https%3A%2F%2Fwww.munzee.com%2Fm%2Fthegr8simondo%2F718) at [50.9193318%2C -1.3548211](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp19jt6w%2F20.0) by [thegr8simondo](https%3A%2F%2Fwww.munzee.com%2Fm%2Fthegr8simondo)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgoldenjellyfish.png is a physical%3A ![goldenjellyfish](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fgoldenjellyfish.png)%0A* [Riverside-Doggy bin](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob%2F234) at [50.9318288%2C -1.3761882](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18xvgk%2F20.0) by [HideyRob](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Ftreefrog.png is a physical%3A ![treefrog](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Ftreefrog.png)%0A* [Riverside-Doggy bin](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob%2F251) at [50.9321511%2C -1.3799991](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18xgj7%2F20.0) by [HideyRob](https%3A%2F%2Fwww.munzee.com%2Fm%2FHideyRob)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fbluewaterballoon.png is a virtual%3A ![bluewaterballoon](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fbluewaterballoon.png)%0A* [Quick Deploy by OldFruits](https%3A%2F%2Fwww.munzee.com%2Fm%2FOldFruits%2F3195) at [50.931883068539%2C -1.3997696870026175](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18puex%2F20.0) by [OldFruits](https%3A%2F%2Fwww.munzee.com%2Fm%2FOldFruits)%0A%0A2412 is a virtual%3A ![sirprizewheel](2412)%0A* [Quick Deploy by Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5736) at [50.931607153173%2C -1.4053645126023184](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pbdh%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Quick Deploy by Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5737) at [50.93227142538%2C -1.403881113938212](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pctz%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A* [Quick Deploy by Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia%2F5738) at [50.931828578178%2C -1.4015974610119315](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcp18pg7k%2F20.0) by [Brazilia](https%3A%2F%2Fwww.munzee.com%2Fm%2FBrazilia)%0A%0Ahttps%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpolyp.png is a virtual%3A ![polyp](https%3A%2F%2Fmunzee.global.ssl.fastly.net%2Fimages%2Fpins%2Fpolyp.png)%0A* [Totton College Bus Stop Jellyfish Munzee](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmrandcr%2F259) at [50.92029586312634%2C -1.5077585863632805](https%3A%2F%2Fwww.munzee.com%2Fmap%2Fgcnctty04%2F20.0) by [mrandcr](https%3A%2F%2Fwww.munzee.com%2Fm%2Fmrandcr)`

**Comment by Technical-13** [comment]
Invalid request.

**Comment by JonnyTech** [comment]
Yep, but can you extract the new virtual types from the request?
