### ISSUE TITLE
Unknown types: [ "physical", "pb&jellyfish" ], [ "virtual", "planulalarva" ], [ "virtual", "polypwithbulbs" ], [ "virtual", "virtualonyx" ], [ "virtual", "virtualcitrine" ], [ "virtual", "ametust" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#38]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/yellowwaterballoon.png is a virtual: ![yellowwaterballoon](https://munzee.global.ssl.fastly.net/images/pins/yellowwaterballoon.png)
* [Bumble Bee #1](https://www.munzee.com/m/war1man/12418) at [51.9018034, -0.5153045898](https://www.munzee.com/map/gcpxk22vb/20.0) by [war1man](https://www.munzee.com/m/war1man)

https://munzee.global.ssl.fastly.net/images/pins/pb&jellyfish.png is a physical: ![pb&jellyfish](https://munzee.global.ssl.fastly.net/images/pins/pb&jellyfish.png)
* [Green box](https://www.munzee.com/m/mickyz/3607) at [50.886658332716, -1.3208669889731](https://www.munzee.com/map/gcp13zwhm/20.0) by [mickyz](https://www.munzee.com/m/mickyz)

https://munzee.global.ssl.fastly.net/images/pins/planulalarva.png is a virtual: ![planulalarva](https://munzee.global.ssl.fastly.net/images/pins/planulalarva.png)
* [Bursledon](https://www.munzee.com/m/tonydev/4568) at [50.889022528943, -1.2962132198326515](https://www.munzee.com/map/gcp1d804h/20.0) by [tonydev](https://www.munzee.com/m/tonydev)
* [Jellyfish @ M27  by Sandy13](https://www.munzee.com/m/Sandy13/5100) at [50.90325260259, -1.3149959277839685](https://www.munzee.com/map/gcp1d4dky/20.0) by [Sandy13](https://www.munzee.com/m/Sandy13)

https://munzee.global.ssl.fastly.net/images/pins/polypwithbulbs.png is a virtual: ![polypwithbulbs](https://munzee.global.ssl.fastly.net/images/pins/polypwithbulbs.png)
* [Quick Deploy by MogwaiLiz](https://www.munzee.com/m/MogwaiLiz/2144) at [50.890470990596, -1.303271443833495](https://www.munzee.com/map/gcp1d26fr/20.0) by [MogwaiLiz](https://www.munzee.com/m/MogwaiLiz)

https://munzee.global.ssl.fastly.net/images/pins/virtualonyx.png is a virtual: ![virtualonyx](https://munzee.global.ssl.fastly.net/images/pins/virtualonyx.png)
* [Quick Deploy by Pixiewix](https://www.munzee.com/m/Pixiewix/4281) at [50.899178581143, -1.4071459927191654](https://www.munzee.com/map/gcncxczm5/20.0) by [Pixiewix](https://www.munzee.com/m/Pixiewix)
* [Quick Deploy by chimem](https://www.munzee.com/m/chimem/3607) at [50.936336716805, -1.4048630590407356](https://www.munzee.com/map/gcp1b09j8/20.0) by [chimem](https://www.munzee.com/m/chimem)
* [Lovers Onyx](https://www.munzee.com/m/Brazilia/5663) at [50.932861039956, -1.4018979488998582](https://www.munzee.com/map/gcp1b051m/20.0) by [Brazilia](https://www.munzee.com/m/Brazilia)
* [Lovers Onyx](https://www.munzee.com/m/TinyTrio/3902) at [50.932623940715, -1.4018051962347329](https://www.munzee.com/map/gcp1b050p/20.0) by [TinyTrio](https://www.munzee.com/m/TinyTrio)
* [Southampton Old Cemetary Onyx](https://www.munzee.com/m/Brazilia/5661) at [50.921833014014, -1.4149567393025393](https://www.munzee.com/map/gcncxy19j/20.0) by [Brazilia](https://www.munzee.com/m/Brazilia)

https://munzee.global.ssl.fastly.net/images/pins/virtualcitrine.png is a virtual: ![virtualcitrine](https://munzee.global.ssl.fastly.net/images/pins/virtualcitrine.png)
* [Quick Deploy by Pixiewix](https://www.munzee.com/m/Pixiewix/4556) at [50.903684625046, -1.397616080913167](https://www.munzee.com/map/gcp184wr3/20.0) by [Pixiewix](https://www.munzee.com/m/Pixiewix)
* [Quick Deploy by Pixiewix](https://www.munzee.com/m/Pixiewix/4276) at [50.915180047415, -1.523991754256997](https://www.munzee.com/map/gcnctkf62/20.0) by [Pixiewix](https://www.munzee.com/m/Pixiewix)
* [Calmore Corner Virtual Citrine](https://www.munzee.com/m/mrandcr/158) at [50.91750418678237, -1.5056894203123647](https://www.munzee.com/map/gcncttpxg/20.0) by [mrandcr](https://www.munzee.com/m/mrandcr)
* [Lovers Citrine](https://www.munzee.com/m/Brazilia/5664) at [50.932444881543, -1.4027192477123833](https://www.munzee.com/map/gcp18pfwf/20.0) by [Brazilia](https://www.munzee.com/m/Brazilia)
* [Southampton Old Cemetary Citrine](https://www.munzee.com/m/Brazilia/5662) at [50.91968462534, -1.4153798422462103](https://www.munzee.com/map/gcncxv9ke/20.0) by [Brazilia](https://www.munzee.com/m/Brazilia)

https://munzee.global.ssl.fastly.net/images/pins/greenwaterballoon.png is a virtual: ![greenwaterballoon](https://munzee.global.ssl.fastly.net/images/pins/greenwaterballoon.png)
* [NFC Newcliffe Gardens](https://www.munzee.com/m/DynamiteDunx/1819) at [50.9099200858259, -1.30799196660519](https://www.munzee.com/map/gcp1d5zec/20.0) by [DynamiteDunx](https://www.munzee.com/m/DynamiteDunx)

https://munzee.global.ssl.fastly.net/images/pins/ametust.png is a virtual: ![ametust](https://munzee.global.ssl.fastly.net/images/pins/ametust.png)
* [Virtual Black Munzee World Travels Garden #10](https://www.munzee.com/m/dielange/466) at [50.93542735, -1.331348839](https://www.munzee.com/map/gcp1c8w83/20.0) by [dielange](https://www.munzee.com/m/dielange)

**Comment by Technical-13** [comment]
Resolved in mentioned commits
