### ISSUE TITLE
Unknown type: [ "virtual", "puffle" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#40]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/puffle.png is a virtual: ![puffle](https://munzee.global.ssl.fastly.net/images/pins/puffle.png)
* [Bumble Bee @ Dunstable, UK](https://www.munzee.com/m/halizwein/6108) at [51.90252205, -0.510412565](https://www.munzee.com/map/gcpxk2s64/20.0) by [halizwein](https://www.munzee.com/m/halizwein)

**Comment by Technical-13** [comment]
Added in above commit.
