### ISSUE TITLE
Unknown type: [ "virtual", "ametust" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#41]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/ametust.png is a virtual: ![ametust](https://munzee.global.ssl.fastly.net/images/pins/ametust.png)
* [Houndwell Park MVM](https://www.munzee.com/m/staticalbatross/875) at [50.903294133154, -1.402559220790863](https://www.munzee.com/map/gcp184dtn/20.0) by [staticalbatross](https://www.munzee.com/m/staticalbatross)

**Comment by Technical-13** [comment]
Already in the DB, please update your version.
