### ISSUE TITLE
Unknown type: [ "physical", "boxjellyfish" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#42]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/boxjellyfish.png is a physical: ![boxjellyfish](https://munzee.global.ssl.fastly.net/images/pins/boxjellyfish.png)
* [deZmondo's dreamy deploys 12](https://www.munzee.com/m/Dezmondo/1251) at [53.474665946622, -2.2504450183853](https://www.munzee.com/map/gcw2hyc29/20.0) by [Dezmondo](https://www.munzee.com/m/Dezmondo)

**Comment by Technical-13** [comment]
Added in above commit.
