### ISSUE TITLE
Unknown types [ "physical", "minotaurcyclops" ]

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#43]
Found unknown mapMarker types:

https://munzee.global.ssl.fastly.net/images/pins/minotaurcyclops.png is a physical: ![minotaurcyclops](https://munzee.global.ssl.fastly.net/images/pins/minotaurcyclops.png)
* [munzee town 11](https://www.munzee.com/m/bobadams/5710) at [53.47549893898282, -2.235357100146111](https://www.munzee.com/map/gcw2jnum2/20.0) by [bobadams](https://www.munzee.com/m/bobadams)

**Comment by Technical-13** [comment]
This is already in the list - update your script.
