### ISSUE TITLE
Updating script

### ISSUE THREAD

**Issue by JonnyTech** [Technical-13/MunzeeMap-Filter#44]
@Technical-13 can you please advise how to update the userscript? There are elements that I have submitted to be added and you have committed to this repo but still show up in a dialog when browsing the map.

I have tried uninstalling the script and then reinstalling. Since the script version is `2020.07.07.1720` then I suspect that the `@resource` files are not being updated but unsure how to check.

Install location: `https://raw.githubusercontent.com/Technical-13/MunzeeMap-Filter/master/MunzeeMap-Filter.js`
Browser version: Firefox 79.0 64 bit
Operating system: Debian Linux 10 Buster
Extensions: Violentmonkey v2.12.7

Thanks.

**Comment by JonnyTech** [comment]
Looking at the commit history, `PRBs.json` has been updated, but this file is not referenced by any other file in this repo. Am I missing something?

**Comment by Technical-13** [comment]
Click here: 
![image](https://user-images.githubusercontent.com/4294498/90077307-cb937100-dccf-11ea-933b-db536ca007f3.png)
