### ISSUE TITLE
Captured / Owned virtual munzees not considered Blastable.

### ISSUE THREAD

**Issue by sohcah** [Technical-13/MunzeeMap-Filter#8]
Captured and Owned virtual munzees are always considered "Non-Blastable". Some of these munzees should count as Blastable. If people want to hide Captured and Owned, they can do so with separate filters. They should still count as Blastable IMO.

**Comment by Technical-13** [comment]
When are they blastable?

**Comment by sohcah** [comment]
Well, the munzees are blastable, even if not blastable by you. It would be especially useful to display ALL blastable munzees, including ones you've capped, when planning with other players and for evos that are soon-to-evolve.

**Comment by Technical-13** [comment]
You can't capture an owned or captured icon, never mind blast them.  If you want to see if they're blastable by someone else, that someone else should log in and check their map.  As far as "soon to evolve" evos go, there's not a lot of information on the cycle of an evo in the map.  I will have information on trails (and their multiple stages) and destinations (and the number of available rooms) at some point after I get the toggle button hover working like I want it (haven't started working on it yet).
